#
# Basic settings.
#
# url: http://localhost:4000
# baseurl: ""
url: http://gk438.github.io
baseurl: 
title: gk438
description: Eat, Sleep, Code, Hack
#avatar: /assets/img/ogp.png
avatar: https://avatars1.githubusercontent.com/u/16232201
# language: ja
language: en

#
# Icons
#
icons:
  rss: true
  email:
  github: gk438
  tumblr: gk438

# Prettify url.
#
permalink: pretty

# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 5

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

# Social.
#
share_buttons:
  twitter: true


include: ["_pages"]

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes", "no_intra_emphasis"]
highlighter: pygments

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
